name: chain-docs

on:
  push:
    branches: [ dev , master ]
    paths:
    - 'docs/**'
    - '!README.md'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: ci
      env:
        MASTER_AWS_ACCESS_KEY_ID: ${{ secrets.MASTER_AWS_ACCESS_KEY_ID }}
        MASTER_AWS_SECRET_ACCESS_KEY: ${{ secrets.MASTER_AWS_SECRET_ACCESS_KEY }}
        MASTER_BUCKET_NAME: ${{ secrets.MASTER_BUCKET_NAME }}
        MASTER_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.MASTER_CLOUDFRONT_DISTRIBUTION_ID }}
        MASTER_REGION: ${{ secrets.MASTER_REGION }}
        STAGING_AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY_ID }}
        STAGING_AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_ACCESS_KEY }}
        STAGING_BUCKET_NAME: ${{ secrets.STAGING_BUCKET_NAME }}
        STAGING_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.STAGING_CLOUDFRONT_DISTRIBUTION_ID }}
        STAGING_REGION: ${{ secrets.STAGING_REGION }}
      run: |
        . ci/scripts/prepare
        ci/scripts/build
        ci/scripts/deploy
